### ISSUE TITLE
/config directory missing? or can you give a demo for the same?

### ISSUE THREAD

**Issue by amexn-me** [takiuddin93/ChatApp#1]

**Comment by takiuddin93** [comment]
I have deliberately removed it from git since it has my agora and firebase API_KEY's

to make it work for you

make a folder inside of **lib** directory named **configs** and inside make two files

agora_configs.dart
const APP_ID = '_YOUR_AGORA_API_KEY_';

and

firebase_configs.dart
const SERVER_KEY = '_YOUR_FIREBASE_SERVER_KEY_';

then your issue will be fixed.

**Comment by amexn-me** [comment]
Great, I thought the demo config files unfortunately ended up in .gitignore.

And thanks for that.
